id: IDECA54CE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T06:36:06+00:00'
last_modified: '2022-06-08T02:22:24.291509+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29236
  title: བདེན་འཚོལ་སྙིང་སྟོབས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '4343':
      image_group_id: I5257
      title: ''
      total_pages: 612
      order: 1
      base_file: 4343.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
